// =============================================================
// transaction.entity.ts – Immutable AFT financial log
// IMPORTANT: No UPDATE/DELETE allowed per casino audit standards
// =============================================================
import {
  Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Index,
} from 'typeorm';

export enum TransactionType {
  TOURNAMENT_PUMP     = 'tournament_pump',
  TOURNAMENT_WITHDRAW = 'tournament_withdraw',
  JACKPOT_CASHABLE    = 'jackpot_cashable',
  JACKPOT_RESTRICTED  = 'jackpot_restricted',
}

export enum TransactionStatus {
  PENDING = 'pending',
  SUCCESS = 'success',
  FAILED  = 'failed',
  RETRY   = 'retry',
}

@Entity('transactions')
export class TransactionEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Index()
  @Column({ type: 'varchar', length: 36, unique: true })
  txn_id: string;             // UUID generated by server

  @Column({ type: 'varchar', length: 50 })
  machine_id: string;

  @Column({ type: 'enum', enum: TransactionType })
  type: TransactionType;

  @Column({ type: 'enum', enum: TransactionStatus, default: TransactionStatus.PENDING })
  status: TransactionStatus;

  @Column({ type: 'bigint' })
  amount: number;             // Credits

  @Column({ type: 'smallint', nullable: true })
  aft_status_code: number;    // Raw AFT response code from machine

  @Column({ type: 'int', nullable: true })
  tournament_id: number;

  @CreateDateColumn()
  created_at: Date;           // Append-only: never update this row
}
